<?php
include_once 'setting.inc.php';

$_lang['dashamail'] = 'DashaMail';
$_lang['dashamail_api_response_code_2'] = 'Ошибка при добавлении в базу';
$_lang['dashamail_api_response_code_3'] = 'Заданы не все необходимые параметры';
$_lang['dashamail_api_response_code_4'] = 'Нет данных при выводе';
$_lang['dashamail_api_response_code_5'] = 'У пользователя нет адресной базы с таким id';
$_lang['dashamail_api_response_code_6'] = 'Некорректный email-адрес';
$_lang['dashamail_api_response_code_7'] = 'Такой пользователь уже есть в этой адресной базе';
$_lang['dashamail_api_response_code_8'] = 'Лимит по количеству активных подписчиков на тарифном плане клиента';
$_lang['dashamail_api_response_code_9'] = 'Нет такого подписчика у клиента';
$_lang['dashamail_api_response_code_10'] = 'Пользователь уже отписан';
$_lang['dashamail_api_response_code_11'] = 'Нет данных для обновления подписчика';
$_lang['dashamail_api_response_code_12'] = 'Не заданы элементы списка';
$_lang['dashamail_api_response_code_13'] = 'Не задано время рассылки';
$_lang['dashamail_api_response_code_14'] = 'Не задан заголовок письма';
$_lang['dashamail_api_response_code_15'] = 'Не задано поле От Кого?';
$_lang['dashamail_api_response_code_16'] = 'Не задан обратный адрес';
$_lang['dashamail_api_response_code_17'] = 'Не задана ни html ни plain_text версия письма';
$_lang['dashamail_api_response_code_18'] = 'Нет ссылки отписаться в тексте рассылки. Пример ссылки: отписаться';
$_lang['dashamail_api_response_code_19'] = 'Нет ссылки отписаться в тексте рассылки';
$_lang['dashamail_api_response_code_20'] = 'Задан недопустимый статус рассылки';
$_lang['dashamail_api_response_code_21'] = 'Рассылка уже отправляется';
$_lang['dashamail_api_response_code_22'] = 'У вас нет кампании с таким campaign_id';
$_lang['dashamail_api_response_code_23'] = 'Нет такого поля для сортировки';
$_lang['dashamail_api_response_code_24'] = 'Заданы недопустимые события для авторассылки';
$_lang['dashamail_api_response_code_25'] = 'Загружаемый файл уже существует';
$_lang['dashamail_api_response_code_26'] = 'Загружаемый файл больше 5 Мб';
$_lang['dashamail_api_response_code_27'] = 'Файл не найден';
$_lang['dashamail_api_response_code_28'] = 'Указанный шаблон не существует';
$_lang['dashamail_api_response_code_100'] = 'Неверные данные для подключения API';
$_lang['dashamail_api_response_code_101'] = 'Несуществующий метод API или указан некорректный метод API';